### PR TITLE
Change the dev URL port number according to docz

### PR DESCRIPTION
**Pull request by aimenbatool**
Just a minor fix.
Port mentioned in [Contribution guide](https://github.com/ReactJSGirls/reactjsgirls-docs/blob/master/Contributing.md) is 3000 while it's running at 5000.  Port number is updated in this PR.

### CODE REVIEW

**Comment by gaearon** [comment]
Oops sorry about this!

**Comment by SaraVieira** [comment]
Thank you !!

**Comment by aimenbatool** [comment]
Thanks, @SaraVieira for accepting my PR. :)

Looking forward to contributing more on this repo.

**Comment by aimenbatool** [comment]
By the way, I am new to open source & I started my journey 3 days back with my first [PR](https://github.com/mozilla-frontend-infra/js-perf-dashboard/pull/75) at Mozilla's repo. 

I am working on Node & React these days. I am looking for opensource projects in this area.
@SaraVieira & @gaearon I would appreciate if you guys recommend me some good opensource projects which are beginner friendly.
Thanks.

**Pull request merged**
